- name: inbstalling packages using loops
  hosts: local
  connection: local
  tasks:
  - name: installing packages
    ansible.builtin.package:
      msg: "installing packages {{ items }}"
  loops:
    - git
    - mysql
    - tree