- name: multiple plays
  hosts: local
  connection: local
  tasks:
  - name: play1
    ansible.builtin.debug:
      msg: "hellow world"
  - name: play 2
    ansible.builtin.debug:
      msg: "learning devops"