- name: install nginx
  hosts: web
  tasks: 
  - name: installing nginx
    ansible.builtin.package:
      name: nginx
      state: installed
  - name: started nginx
    ansible.builtin.service:
      service: nginx
      state: present