- name: through prompt variables
  hosts: local
  connection: local
  vars_prompt:
    - name: course
      prompt: please enter the course name
      private: false
    - name: trainer
      prompt: pleasxe enter you trainer
      private: false
  tasks:
  - name: print the varaibales through prompt
    ansible.builtin.debug:
      msg: "I'm learning {{ course }} and my trainer in {{ trainer }}"